version: "3.7"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./back-end/
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
  frontend:
    build: ./front-end/
    ports:
      - "3000:3000"
    depends_on:
      - backend
