version: '3.7'
services:
    db:
        image: mongo
        ports:
            - '27017:27017'
    backend:
        build: ./
        ports:
            - '4000:4000'
        depends_on:
            - db
        links:
            - db
